import { Mail, MapPin, MessageCircle, Phone } from "lucide-react";
import type { PublicStore } from "@/lib/queries/stores";
import { buildDirectionsHref, buildStoreWhatsAppHref, openingHoursEntries, storeAddress } from "@/lib/stores/store-utils";

export function StoreCard({ store }: { store: PublicStore }) {
  const directionsHref = buildDirectionsHref(store);
  const whatsAppHref = buildStoreWhatsAppHref(store.whatsapp);
  const hours = openingHoursEntries(store.opening_hours);
  return <article className="flex h-full flex-col border bg-surface p-6"><h2 className="text-2xl">{store.name}</h2><address className="mt-4 not-italic leading-7 text-muted">{storeAddress(store)}</address>{hours.length ? <section className="mt-5"><h3 className="text-sm font-semibold uppercase tracking-[.12em] text-muted">Opening hours</h3><dl className="mt-2 grid gap-1 text-sm">{hours.map(([day, time]) => <div key={day} className="flex justify-between gap-3"><dt>{day}</dt><dd className="text-right text-muted">{time}</dd></div>)}</dl></section> : null}<div className="mt-6 flex flex-wrap gap-3 border-t pt-5">{store.phone ? <a href={`tel:${store.phone.replace(/\s+/g, "")}`} className="inline-flex min-h-11 items-center gap-2 border px-3 text-sm font-semibold hover:bg-surface-muted" aria-label={`Call ${store.name}`}><Phone size={17} aria-hidden />Call</a> : null}{store.email ? <a href={`mailto:${store.email}`} className="inline-flex min-h-11 items-center gap-2 border px-3 text-sm font-semibold hover:bg-surface-muted" aria-label={`Email ${store.name}`}><Mail size={17} aria-hidden />Email</a> : null}{whatsAppHref ? <a href={whatsAppHref} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center gap-2 border px-3 text-sm font-semibold hover:bg-surface-muted" aria-label={`Open a WhatsApp enquiry for ${store.name} in a new tab`}><MessageCircle size={17} aria-hidden />WhatsApp</a> : null}{directionsHref ? <a href={directionsHref} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center gap-2 border px-3 text-sm font-semibold hover:bg-surface-muted" aria-label={`Get directions to ${store.name} in a new tab`}><MapPin size={17} aria-hidden />Get Directions</a> : null}</div></article>;
}
