import Image from "next/image";
import Link from "next/link";
import type { CatalogProduct } from "@/lib/catalog/catalog-filters";
import { applicationLabels, labelProductValues, roomLabels, stockStatusLabels } from "@/lib/catalog/product-labels";
import { effectivePrice } from "@/lib/catalog/catalog-filters";
import { formatPrice } from "@/lib/utils";
import { CompareClearButton, ComparePageControls, CompareUrlSync } from "@/components/compare/ComparePageControls";

const fallback = "—";
const display = (value: string | number | null | undefined) => value === null || value === undefined || value === "" ? fallback : String(value);

export function CompareResults({ products }: { products: CatalogProduct[] }) {
  if (!products.length) return <section className="mt-8 border bg-surface p-8"><p className="max-w-xl text-muted">Select two or three tiles to compare their specifications side by side.</p><Link href="/tiles" className="mt-5 inline-flex min-h-11 items-center bg-primary px-4 font-semibold text-primary-foreground">Browse Tiles</Link></section>;
  if (products.length === 1) { const product = products[0]; const image = product.product_images[0]; const href = product.category ? `/tiles/${product.category.slug}/${product.slug}` : "/tiles"; return <><CompareUrlSync products={[product.slug]} /><section className="mt-8 border bg-surface p-6"><div className="grid gap-5 sm:grid-cols-[12rem_1fr]"><div className="relative aspect-square bg-surface-muted">{image ? <Image src={image.image_url} alt={image.alt_text ?? `${product.name} tile render`} fill unoptimized className="object-cover" /> : null}</div><div><p className="text-sm font-semibold text-primary">{product.category?.name ?? "Tile collection"}</p><h2 className="mt-1 text-2xl">{product.name}</h2><p className="mt-2 text-muted">Add at least one more tile to start comparing.</p><p className="mt-3 font-semibold">{formatPrice(effectivePrice(product))}</p><div className="mt-5 flex flex-wrap gap-3"><Link href="/tiles" className="inline-flex min-h-11 items-center bg-primary px-4 font-semibold text-primary-foreground">Browse More Tiles</Link><Link href={href} className="inline-flex min-h-11 items-center border px-4 font-semibold">View Tile</Link><ComparePageControls slug={product.slug} name={product.name} /></div></div></div><div className="mt-5"><CompareClearButton /></div></section></>; }
  const rows: Array<[string, (product: CatalogProduct) => string]> = [
    ["Category", (p) => display(p.category?.name)], ["Price", (p) => formatPrice(effectivePrice(p))], ["Regular price", (p) => p.sale_price !== null && p.sale_price < p.price ? formatPrice(p.price) : fallback], ["Size", (p) => display(p.size_label)], ["Width", (p) => p.width_mm ? `${p.width_mm} mm` : fallback], ["Height", (p) => p.height_mm ? `${p.height_mm} mm` : fallback], ["Thickness", (p) => p.thickness_mm ? `${p.thickness_mm} mm` : fallback], ["Colour", (p) => display(p.colour)], ["Finish", (p) => display(p.finish)], ["Material", (p) => display(p.material)], ["Applications", (p) => labelProductValues(p.applications, applicationLabels).join(", ") || fallback], ["Suitable spaces", (p) => labelProductValues(p.rooms, roomLabels).join(", ") || fallback], ["Slip rating", (p) => display(p.slip_rating)], ["Water absorption", (p) => display(p.water_absorption)], ["Stock status", (p) => stockStatusLabels[p.stock_status] ?? display(p.stock_status)], ["SKU", (p) => display(p.sku)], ["New", (p) => p.is_new ? "Yes" : fallback], ["Featured", (p) => p.is_featured ? "Yes" : fallback],
  ];
  return <><CompareUrlSync products={products.map((product) => product.slug)} /><div className="mt-8 flex flex-wrap items-center justify-between gap-3"><p className="text-muted">Comparing {products.length} tiles.</p><CompareClearButton /></div><div role="region" aria-label="Side-by-side tile comparison" tabIndex={0} className="mt-6 overflow-x-auto border"><table className="min-w-[760px] w-full border-collapse text-left text-sm"><thead><tr className="bg-surface-muted"><th scope="col" className="min-w-40 p-4 font-semibold">Tile</th>{products.map((product) => { const image = product.product_images[0]; const href = product.category ? `/tiles/${product.category.slug}/${product.slug}` : "/tiles"; return <th scope="col" key={product.id} className="min-w-64 p-4 align-top"><div className="relative aspect-[4/3] bg-surface">{image ? <Image src={image.image_url} alt={image.alt_text ?? `${product.name} tile render`} fill unoptimized className="object-cover" /> : null}</div><p className="mt-3 text-sm text-primary">{product.category?.name ?? "Tile collection"}</p><Link href={href} className="mt-1 block text-lg font-semibold hover:text-primary">{product.name}</Link><p className="mt-2">{formatPrice(effectivePrice(product))}{product.sale_price !== null && product.sale_price < product.price ? <><br /><span className="font-normal text-muted line-through">{formatPrice(product.price)}</span><span className="ml-2 font-normal text-muted">Regular price</span></> : null}</p><p className="mt-2 text-sm text-muted">{stockStatusLabels[product.stock_status] ?? product.stock_status}</p><ComparePageControls slug={product.slug} name={product.name} /></th>; })}</tr></thead><tbody>{rows.map(([label, value]) => <tr key={label} className="border-t"><th scope="row" className="bg-surface-muted/50 p-4 font-semibold">{label}</th>{products.map((product) => <td key={product.id} className="p-4 align-top text-muted">{value(product)}</td>)}</tr>)}</tbody></table></div></>;
}
