import Image from "next/image";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Container } from "@/components/ui/container";
import { Reveal } from "@/components/ui/Reveal";

export function BrandStorySection() {
  return <section className="bg-surface-muted py-14 sm:py-20"><Container><Reveal className="editorial-split"><Image src="/images/editorial/about-interior.webp" alt="Illustrative contemporary showroom displaying architectural surfaces" width={1440} height={1080} sizes="(max-width: 767px) 92vw, 48vw" className="editorial-image aspect-[4/3]" /><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-primary">A clearer digital experience</p><h2 className="mt-4 text-4xl sm:text-5xl">Tiles, considered from the first click.</h2><p className="mt-5 text-base leading-8 text-muted">Timeless Tiles brings tile discovery into a clearer digital experience—helping customers explore collections, understand specifications, and connect with the right options for their spaces.</p><div className="mt-6 flex flex-wrap gap-5 text-sm font-semibold text-primary"><Link href="/about" className="inline-flex min-h-11 items-center gap-2">Learn About Us <ArrowRight size={16} aria-hidden /></Link><Link href="/guides" className="inline-flex min-h-11 items-center gap-2">Explore Tile Guides <ArrowRight size={16} aria-hidden /></Link></div></div></Reveal></Container></section>;
}
export function FinalCtaSection() {
  return <section className="bg-surface py-14 sm:py-20"><Container><Reveal><div className="relative isolate overflow-hidden rounded-sm bg-[#0C1720] px-6 py-12 text-white sm:px-12"><Image src="/images/home/hero-kitchen.webp" alt="" fill sizes="100vw" className="-z-2 object-cover" /><div className="absolute inset-0 -z-1 bg-[#0C1720]/70" /><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#E5B663]">Explore. Compare. Connect.</p><h2 className="mt-4 text-4xl sm:text-5xl">Planning your next space?</h2><p className="mt-4 max-w-xl leading-7 text-white/90">Browse the collection, find a fictional demo location, or request help choosing the right surfaces for your project.</p><div className="mt-7 flex flex-wrap gap-3"><Button href="/tiles">Explore Tiles</Button><Button href="/stores" variant="outline" className="border-white/60 text-white hover:bg-white/10 hover:text-white">Find a Store</Button><Button href="/contact?intent=quote" variant="outline" className="border-white/60 text-white hover:bg-white/10 hover:text-white">Get a Quote</Button></div></div></Reveal></Container></section>;
}
